source :rubygems
gem 'sinatra'
gem 'thin', '1.2.7'
gem 'haml', '3.1.4'
gem 'sass', '3.1.12'
gem 'curb', '0.7.17'
gem 'activeresource', '3.1.3'
gem 'rest-client'
gem 'sinatra-contrib'
gem 'httparty'
gem 'mongo'
gem 'mail'
gem 'fastercsv'
gem 'airbrake'
gem 'smoke_monster'